### PR TITLE
seed data to test contract statuses and associations

### PR DESCRIPTION
**Pull request by ooong**

### CODE REVIEW

**Comment by Asterids** [comment]
I know we didn't make a 'unique' constraint for our Contract model, but I think each contract address should/will be unique - for instance, the same contract could not be both 'Pending' and 'Completed' at the same time.

**Comment by ooong** [comment]
ah so I added 'TEST's throughout the contract instances to make them unique- I think I got them all but let me double check @Asterids

**Comment by Asterids** [comment]
Oh, I see them now! I only saw one of them at first, in the same spot in all three. Okay, fair enough!

**Comment by ooong** [comment]
okay cool! Yeah they all start to blur together lol

**Review by Asterids — APPROVED** [review]

**Pull request merged**
